// Code generated by protoc-gen-go.
// source: collectd.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	collectd.proto

It has these top-level messages:
	DispatchValuesRequest
	DispatchValuesReply
	QueryValuesRequest
	QueryValuesReply
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import collectd_types "collectd.org/rpc/types"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The arguments to DispatchValues.
type DispatchValuesRequest struct {
	Values *collectd_types.ValueList `protobuf:"bytes,1,opt,name=values" json:"values,omitempty"`
}

func (m *DispatchValuesRequest) Reset()                    { *m = DispatchValuesRequest{} }
func (m *DispatchValuesRequest) String() string            { return proto.CompactTextString(m) }
func (*DispatchValuesRequest) ProtoMessage()               {}
func (*DispatchValuesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DispatchValuesRequest) GetValues() *collectd_types.ValueList {
	if m != nil {
		return m.Values
	}
	return nil
}

// The response from DispatchValues.
type DispatchValuesReply struct {
}

func (m *DispatchValuesReply) Reset()                    { *m = DispatchValuesReply{} }
func (m *DispatchValuesReply) String() string            { return proto.CompactTextString(m) }
func (*DispatchValuesReply) ProtoMessage()               {}
func (*DispatchValuesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// The arguments to QueryValues.
type QueryValuesRequest struct {
	// Query by the fields of the identifier. Only return values matching the
	// specified shell wildcard patterns (see fnmatch(3)). Use '*' to match
	// any value.
	Identifier *collectd_types.Identifier `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *QueryValuesRequest) Reset()                    { *m = QueryValuesRequest{} }
func (m *QueryValuesRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryValuesRequest) ProtoMessage()               {}
func (*QueryValuesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryValuesRequest) GetIdentifier() *collectd_types.Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

// The response from QueryValues.
type QueryValuesReply struct {
	Values []*collectd_types.ValueList `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *QueryValuesReply) Reset()                    { *m = QueryValuesReply{} }
func (m *QueryValuesReply) String() string            { return proto.CompactTextString(m) }
func (*QueryValuesReply) ProtoMessage()               {}
func (*QueryValuesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueryValuesReply) GetValues() []*collectd_types.ValueList {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*DispatchValuesRequest)(nil), "service.DispatchValuesRequest")
	proto.RegisterType((*DispatchValuesReply)(nil), "service.DispatchValuesReply")
	proto.RegisterType((*QueryValuesRequest)(nil), "service.QueryValuesRequest")
	proto.RegisterType((*QueryValuesReply)(nil), "service.QueryValuesReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Collectd service

type CollectdClient interface {
	// Dispatch collected values to collectd.
	DispatchValues(ctx context.Context, in *DispatchValuesRequest, opts ...grpc.CallOption) (*DispatchValuesReply, error)
	// Query a list of values available from collectd's value cache.
	QueryValues(ctx context.Context, in *QueryValuesRequest, opts ...grpc.CallOption) (*QueryValuesReply, error)
}

type collectdClient struct {
	cc *grpc.ClientConn
}

func NewCollectdClient(cc *grpc.ClientConn) CollectdClient {
	return &collectdClient{cc}
}

func (c *collectdClient) DispatchValues(ctx context.Context, in *DispatchValuesRequest, opts ...grpc.CallOption) (*DispatchValuesReply, error) {
	out := new(DispatchValuesReply)
	err := grpc.Invoke(ctx, "/service.Collectd/DispatchValues", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectdClient) QueryValues(ctx context.Context, in *QueryValuesRequest, opts ...grpc.CallOption) (*QueryValuesReply, error) {
	out := new(QueryValuesReply)
	err := grpc.Invoke(ctx, "/service.Collectd/QueryValues", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Collectd service

type CollectdServer interface {
	// Dispatch collected values to collectd.
	DispatchValues(context.Context, *DispatchValuesRequest) (*DispatchValuesReply, error)
	// Query a list of values available from collectd's value cache.
	QueryValues(context.Context, *QueryValuesRequest) (*QueryValuesReply, error)
}

func RegisterCollectdServer(s *grpc.Server, srv CollectdServer) {
	s.RegisterService(&_Collectd_serviceDesc, srv)
}

func _Collectd_DispatchValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectdServer).DispatchValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Collectd/DispatchValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectdServer).DispatchValues(ctx, req.(*DispatchValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collectd_QueryValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectdServer).QueryValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Collectd/QueryValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectdServer).QueryValues(ctx, req.(*QueryValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Collectd_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Collectd",
	HandlerType: (*CollectdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchValues",
			Handler:    _Collectd_DispatchValues_Handler,
		},
		{
			MethodName: "QueryValues",
			Handler:    _Collectd_QueryValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("collectd.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0xcf, 0xc9,
	0x49, 0x4d, 0x2e, 0x49, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x95, 0xe2, 0x2e, 0xa9, 0x2c, 0x48, 0x2d, 0x86, 0x88, 0x2a, 0x79, 0x71, 0x89,
	0xba, 0x64, 0x16, 0x17, 0x24, 0x96, 0x24, 0x67, 0x84, 0x25, 0xe6, 0x94, 0xa6, 0x16, 0x07, 0xa5,
	0x16, 0x02, 0xc9, 0x12, 0x21, 0x43, 0x2e, 0xb6, 0x32, 0xb0, 0x80, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0xb7, 0x91, 0xa4, 0x1e, 0xdc, 0x3c, 0x88, 0x7e, 0xb0, 0x72, 0x9f, 0xcc, 0xe2, 0x92, 0x20, 0xa8,
	0x42, 0x25, 0x51, 0x2e, 0x61, 0x74, 0xb3, 0x0a, 0x72, 0x2a, 0x95, 0x02, 0xb8, 0x84, 0x02, 0x4b,
	0x53, 0x8b, 0x2a, 0x51, 0xcd, 0xb7, 0xe2, 0xe2, 0xca, 0x4c, 0x49, 0xcd, 0x2b, 0xc9, 0x4c, 0xcb,
	0x4c, 0x2d, 0x82, 0xda, 0x21, 0x85, 0x6e, 0x87, 0x27, 0x5c, 0x45, 0x10, 0x92, 0x6a, 0x25, 0x57,
	0x2e, 0x01, 0x14, 0x13, 0x81, 0xb6, 0xa0, 0xb8, 0x97, 0x99, 0x28, 0xf7, 0x1a, 0x2d, 0x64, 0xe4,
	0xe2, 0x70, 0x86, 0x2a, 0x12, 0xf2, 0xe3, 0xe2, 0x43, 0x75, 0xbc, 0x90, 0x9c, 0x1e, 0x34, 0xc4,
	0xf4, 0xb0, 0x86, 0x90, 0x94, 0x0c, 0x4e, 0x79, 0x90, 0x7b, 0x5c, 0xb9, 0xb8, 0x91, 0xdc, 0x28,
	0x24, 0x0d, 0x57, 0x8c, 0x19, 0x16, 0x52, 0x92, 0xd8, 0x25, 0x81, 0xc6, 0x38, 0x09, 0x45, 0x09,
	0xc0, 0xfd, 0x91, 0x5f, 0x94, 0xae, 0x5f, 0x54, 0x90, 0x9c, 0xc4, 0x06, 0x8e, 0x3a, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x1d, 0x63, 0x20, 0xe2, 0x01, 0x00, 0x00,
}
